version: '3.8'

services:
  redis:
    image: 'redis:6.0.9-alpine'
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  db:
    image: postgres
    restart: always 
    env_file:
      - dev.env # configure postgres
    ports:
        - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  go-api:
      build:
        context: ./go-api
        dockerfile: Dockerfile.dev
      env_file:
      - dev.env # golang env
      volumes:
        - ./go-api:/go/src/app #mouth volumes
      ports:
        - "5000:8080"
      command: air
      depends_on:
        - db
        - redis
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database-data: # named volumes can be managed easier using docker-compose
  redis-data: